version: '3.5'
services:
  consistent:
    image: ka3de/consistent:latest
    hostname: consistent01
    command: ["/app", "-port", "4000", "-api-port", "4001", "-nodelist-dns", "consistent"]
    ports:
      - "4000"
      - "4001"
  
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - consistent
    ports:
      - "8080:8080"
      - "8081:8081"

networks:
  default:
    driver: bridge
    name: consistent
